name: Bump Package Version

on:
  push:
    branches: [ master ]

jobs:
  update-nuget-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Bump version
        uses: SiqiLu/dotnet-bump-version@master
        with:
          version_files: "**/*.csproj"
          version_mask: "0.0.1.0"
          version_overwrite: "*.*.1.*"
