name: publish Expander Template Package

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  PACKAGE_FOLDER: D:\a\LiquidVisions.PanthaRhei.Templates\LiquidVisions.PanthaRhei.Templates\src\package\

jobs:
  push-nuget-packages:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.x
  
    - name: Bump version
      uses: SiqiLu/dotnet-bump-version@master
      with:
        version_files: "**/Expander/LiquidVisions.PanthaRhei.Templates.Expander.csproj"
        version_mask: "0.0.1.0"
        version_overwrite: "*.*.1.*"
    
    - name: Dotnet Pack
      run: |  
        cd Expander/
        dotnet pack -c Release -o ${{env.PACKAGE_FOLDER}}
        
    - name: Publish
      run: dotnet nuget push ${{env.PACKAGE_FOLDER}}*.nupkg --skip-duplicate --no-symbols --source https://nuget.pkg.github.com/liquidvisions/index.json --api-key ${{secrets.GITHUB_TOKEN}}
