name: Update NuGet Package References

on:
  workflow_dispatch:
  repository_dispatch:
    types: [nuget-package-update]

jobs:
  update-nuget-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'  # Change to your required .NET version

      - name: Add Package Token
        run: |
          dotnet nuget remove source github | dotnet nuget add source --username USERNAME --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LiquidVisions/index.json"
        
      - name: Update NuGet packages
        run: |
          find . -name "*.csproj" | while read csproj; do
            dotnet restore "$csproj" | dotnet list "$csproj" package --outdated --include-prerelease | tail -n +3 | awk '{print $1 " " $4}' | while read package version; do
              dotnet add "$csproj" package $package --version $version
            done
          done

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git checkout -b update-nuget-packages
          git add .
          git commit -m "Update NuGet packages to latest versions"

      - name: Push changes to feature branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push -u origin update-nuget-packages

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-nuget-packages
          title: 'Update NuGet packages to latest versions'
          body: 'This PR updates all NuGet packages to their latest versions.'

      - name: Merge Pull Request
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=$(jq -r '.pull_request.number' <<<"${{ steps.create_pr.outputs.pull_request }}")
          gh pr merge $pr_number --merge --admin

