name: Update NuGet Package References

on:
  workflow_dispatch:
  repository_dispatch:
    types: [nuget-package-update]

jobs:
  update-nuget-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'  # Change to your required .NET version

      - name: Add Package Token
        run: |
          dotnet nuget add source --username USERNAME --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LiquidVisions/index.json"
        
      - name: Update NuGet packages
        run: |
          find . -name "*.csproj" | while read csproj; do
            echo "Handling project file: $csproj"
            dotnet restore "$csproj"
            outdated_packages=$(dotnet list "$csproj" package --outdated)
            echo "$outdated_packages"
            echo "$outdated_packages" | tail -n +9 | awk '{print $2 " " $5}' | while read package version; do
              echo "Updating package: $package to version: $version in project file: $csproj"
              dotnet add "$csproj" package $package
            done
          done

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Update NuGet packages to latest versions"
          
      - name: Push changes to master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin HEAD:master
